spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG

demo:
  id: 2
  message: hello from prod

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS