spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG